id = "gta-sbl"
name = "GTA Sanny Builder"
version = "0.1.0"
schema_version = 1
authors = ["Chance Snow <git@chancesnow.me>"]
description = "Sanny Builder scripts for Grand Theft Auto 3D games (GTA3, VC, SA, LCS, and VCS)"
repository = "https://github.com/chances/tree-sitter-gta3"

[grammars.sbl]
# For local dev you can swap this for a file:// URL pointing at the repo root.
repository = "https://github.com/chances/tree-sitter-gta3"
rev = "0082b2012c7fbcb61cb2f726e16f0a5996bf64cf"
